package it.bplus.primitive;

// Generated 5-apr-2011 19.46.29 by Hibernate Tools 3.4.0.CR1


/**
 * Spaziodim generated by hbm2java
 */
public class SpazioDim {

		
	private long id;
	private String id_comune;
	private int id_provincia;
	private int id_area;
	private String id_regione;
	private int id_nazione;

	public SpazioDim() {
	}

	

	public SpazioDim(long id, String id_comune, int id_provincia, int id_area,
			String id_regione, int id_nazione) {
		super();
		this.id = id;
		this.id_comune = id_comune;
		this.id_provincia = id_provincia;
		this.id_area = id_area;
		this.id_regione = id_regione;
		this.id_nazione = id_nazione;
	}



	public long getId() {
		return id;
	}



	public void setId(long id) {
		this.id = id;
	}



	public String getId_comune() {
		return id_comune;
	}



	public void setId_comune(String id_comune) {
		this.id_comune = id_comune;
	}



	public int getId_provincia() {
		return id_provincia;
	}



	public void setId_provincia(int id_provincia) {
		this.id_provincia = id_provincia;
	}



	public int getId_area() {
		return id_area;
	}



	public void setId_area(int id_area) {
		this.id_area = id_area;
	}



	public String getId_regione() {
		return id_regione;
	}



	public void setId_regione(String id_regione) {
		this.id_regione = id_regione;
	}



	public int getId_nazione() {
		return id_nazione;
	}



	public void setId_nazione(int id_nazione) {
		this.id_nazione = id_nazione;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		result = prime * result + id_area;
		result = prime * result
				+ ((id_comune == null) ? 0 : id_comune.hashCode());
		result = prime * result + id_nazione;
		result = prime * result + id_provincia;
		result = prime * result
				+ ((id_regione == null) ? 0 : id_regione.hashCode());
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SpazioDim other = (SpazioDim) obj;
		if (id != other.id)
			return false;
		if (id_area != other.id_area)
			return false;
		if (id_comune == null) {
			if (other.id_comune != null)
				return false;
		} else if (!id_comune.equals(other.id_comune))
			return false;
		if (id_nazione != other.id_nazione)
			return false;
		if (id_provincia != other.id_provincia)
			return false;
		if (id_regione == null) {
			if (other.id_regione != null)
				return false;
		} else if (!id_regione.equals(other.id_regione))
			return false;
		return true;
	}



	@Override
	public String toString() {
		return "SpazioDim [id=" + id + ", id_comune=" + id_comune
				+ ", id_provincia=" + id_provincia + ", id_area=" + id_area
				+ ", id_regione=" + id_regione + ", id_nazione=" + id_nazione
				+ "]";
	}

	
}
